version: '3.7'
services:
  mqtt:
    image: toke/mosquitto
    restart: unless-stopped

  consumer:
    build: 
      context: .
      dockerfile: Dockerfile-consumer
    volumes:
        - .:/app      
    depends_on:
      - mqtt

  producer:
    build: 
      context: .
      dockerfile: Dockerfile-producer
    volumes:
        - .:/app      
    depends_on:
      - mqtt
      
      
      
  


