version: '3.7'
services:
  zookeeper:
    image: zookeeper:3.5.8
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
    networks:
      - kafka-network

  consumer:
    build: ./Docekfile-consumer
    command: python consumer.py
    depends_on:
      - kafka

  producer:
    build: ./Docekfile-producer
    command: python producer.py
    depends_on:
      - kafka



